### ISSUE TITLE
UX/UI work for on Desktop

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#103]
Padding of Windows/Mac OS websites, trending posts, communities, jobs on the right side. Creating a more evenly padded website.

Leading and trailing ends of website, adding dead zones as well.

**Comment by carlosyrodriguez** [comment]
![image](https://github.com/brycemcole/CORE/assets/100539048/b6b7dd6e-5093-4f55-9ee0-c7439dfe6ec2)
Logo top left at home is too high up for example^

**Comment by brycemcole** [comment]
fixed
