### ISSUE TITLE
Name of the user is too small on posts and color for host of the post should be a different color

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#106]
![image](https://github.com/brycemcole/CORE/assets/100539048/36d5dd2e-c692-4d31-965a-ec36627aa189)
![image](https://github.com/brycemcole/CORE/assets/100539048/58cb27b7-5655-4bc9-b26c-a9813eeb7f8c)

**Comment by brycemcole** [comment]
fixed
