### ISSUE TITLE
image previews for posts

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#120]
While browsing, links have photo previews but not images users upload

**Comment by carlosyrodriguez** [comment]
.

**Comment by brycemcole** [comment]
<img width="330" alt="image" src="https://github.com/brycemcole/CORE/assets/92781264/a49dd432-8bb6-47cb-902f-13a6a513ae62">

<img width="330" alt="image" src="https://github.com/brycemcole/CORE/assets/92781264/47c4e223-3875-4c56-a839-970c847a27cc">

fixed
