### ISSUE TITLE
Openings section

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#123]
When favoriting posts it takes you to another website 
![image](https://github.com/brycemcole/CORE/assets/100539048/535a7303-a4ed-4c38-807b-ff3801c88939)

Items are misaligned (see discord posting and how star is more to the right which makes page slide to right while scrolling) 
![image](https://github.com/brycemcole/CORE/assets/100539048/1c3808d7-8301-491f-9930-60f15aafda00)

**Comment by brycemcole** [comment]
fixed
