### ISSUE TITLE
Enhance search results

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#126]
![image](https://github.com/brycemcole/CORE/assets/100539048/d87c1d3c-b9e4-4ce9-8f5d-e413a9e5c88a)

Currently, search results don’t really work too well. Adding this issue just to have it on the list

**Comment by brycemcole** [comment]
<img width="389" alt="image" src="https://github.com/brycemcole/CORE/assets/92781264/229d331e-02af-41e7-8140-9905f6c06ae4">
<img width="389" alt="image" src="https://github.com/brycemcole/CORE/assets/92781264/2fd50ac6-9357-4255-b26d-c30cde332f64">
