### ISSUE TITLE
Post reaction bubble stays static

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#132]
![image](https://github.com/brycemcole/CORE/assets/100539048/dd9e7204-363f-4679-b608-951a5a762905)
When clicking the reaction button of another post, the previous one should fade away

**Comment by carlosyrodriguez** [comment]
![image](https://github.com/brycemcole/CORE/assets/100539048/e40e3853-80b5-4941-b82f-247c912990e9)
Also when clicking a reaction and clicking it to go away, post stays highlighted

**Comment by brycemcole** [comment]
fixed on the actual post pages, i removed the ability to react to pages that way from the home page, didnt really like the idea of reacting to a post without clicking it.
