### ISSUE TITLE
Reactions disappear within 3 seconds and part of it is blocked and does not allow scrolling to see blocked part

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#135]
![image](https://github.com/brycemcole/CORE/assets/100539048/f619b07f-2f65-4801-a29e-bd65e643e755)

i also think it should be smaller and right above the reaction counter to look cleaner

**Comment by brycemcole** [comment]
menu sticks around now until you click somewhere else or click the button again
