### ISSUE TITLE
Profile page not sizing properly & sign in w github & google not aligned properly

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#141]
![image](https://github.com/brycemcole/CORE/assets/100539048/cdc49500-beaf-4384-947d-5febdbd60a3b)

profile^

![image](https://github.com/brycemcole/CORE/assets/100539048/914604d5-ce29-45a9-b95c-74cec08abb86)

**Comment by brycemcole** [comment]
fixed
