### ISSUE TITLE
Replace job descriptions on home for tags of top 3 skills needed for the job

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#151]
![image](https://github.com/brycemcole/CORE/assets/100539048/89fea450-0df4-4b69-8562-4a58ec2db56d)

the text gets cut off so short that the small preview of information isnt very useful, maybe top 3 skills needed or maybe if the job is remote move that as a top seeked tag etc

**Comment by brycemcole** [comment]
removed entirely
