### ISSUE TITLE
Openings and job previews on home page are mostly just netflix

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#153]

**Comment by carlosyrodriguez** [comment]
![image](https://github.com/brycemcole/CORE/assets/100539048/d7097a17-2bd1-42c7-93c9-57dececae85b)

![image](https://github.com/brycemcole/CORE/assets/100539048/7db19df8-277d-4262-9856-80cb05e23812)

**Comment by carlosyrodriguez** [comment]
Also just noticed on that picture, when searching with tags, the padding at both ends is way less than other parts of the website

**Comment by brycemcole** [comment]
lmao i just added like 40 jobs from netflix and it shows them in order so it's gonna do that

**Comment by carlosyrodriguez** [comment]
> lmao i just added like 40 jobs from netflix and it shows them in order so it's gonna do that

Do you think we should put in a system that prevents from showing that? At least for home page so whenever hella jobs get added theres a variety of companies instead of one

**Comment by brycemcole** [comment]
![image](https://github.com/brycemcole/CORE/assets/92781264/f08f2005-e138-46ab-aaa3-2767fe81042b)
![image](https://github.com/brycemcole/CORE/assets/92781264/e9df660e-0005-4c83-b52f-2a0cafc3ecdc)

- jobs on home page are now random
- jobs now show up under posts and are also random

i'm gonna work to get them to show a user's job recommendation on the jobs home page.
