### ISSUE TITLE
Comments replies

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#56]
![image](https://github.com/brycemcole/CORE/assets/100539048/1484f6df-5b6a-4948-89b3-c82078cfdbb0)

**Comment by brycemcole** [comment]
![image](https://github.com/brycemcole/CORE/assets/92781264/5e99f426-bac4-412d-bdd2-de2b54b1cc36)

here's how it looks right now, i'll work on adding the show full nested comments length instead of just how many comments it has.

**Comment by brycemcole** [comment]
comment appearance tweaked and replies too
