### ISSUE TITLE
Updating profile gives internal server error

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#77]
![image](https://github.com/brycemcole/CORE/assets/100539048/05c409d8-cd4e-4973-b40e-8d709ba9ad33)

**Comment by carlosyrodriguez** [comment]
Details are still updated tho

**Comment by brycemcole** [comment]
what did u update that caused this lol

**Comment by carlosyrodriguez** [comment]
> what did u update that caused this lol

Profile pic, job title, linkedin link, github username
