### ISSUE TITLE
Formatting doesn’t show on post previews

### ISSUE THREAD

**Issue by carlosyrodriguez** [brycemcole/CORE#83]
![image](https://github.com/brycemcole/CORE/assets/100539048/c8191b3e-e4e4-492b-80ed-248063c98035)

shows the ** instead of bolding the text, but when you click into the post the text is formatted properly

**Comment by brycemcole** [comment]
it's not gonna show formatting otherwise we might have weird cut off stuff showing up on homepage i'll just make it remove the formatting

**Comment by brycemcole** [comment]
fixed
